from time import sleep as timeout
import time
import base64
import socket
import sys
import os
os.system ('clear')
def homescreen () :
    os.system ('clear')
    print ("          .-;;-. ")
    print ("         / .--. \  ")
    print ("        / /    \ \  ")
    print ("        | |    | |  ")
    print ("        | |.-""-.|  ")
    print ("       ///`.::::.`\   ") 
    print ("      ||| ::/  \ ::;  ")
    print ("      ||; ::\__/ ::;  ")
    print ("        \ \.:::::: /  ")
    print ("        `=`:-..-``  ")
    print (' ')
    print (' ')
    V = input ("\033[1;36m  ﺮﺴㅤﺔﻤﻠڪ  بﺘڪأ \033[1;32m🔑🔒 ==> ")
    if V == 'my brahim' :
        os.system ('clear')
        print ("       .-""-.")
        print ("      / .--. \ ")
        print ("     / /    \ \ ")
        print ("     | |    | |")
        print ("            | |.-""-.")
        print ("           ///`.::::.`\ ")
        print ("          ||| ::/  \ ::;")
        print ("          ||; ::\__/ ::;")
        print ("           \ \ :::::: /")
        print ("            `=:-..-`" )
        print (' ')
        print (' ')
        timeout(1.20)
        print ('.............\033[1;36m(👑YOUR VIP Motawakil👑)\033[92m...............!')
        timeout(6.11)
        print ("")
        print ('.............\033[1;36mلوﺧد  يﺮﭴ\033[92m...............!')
        print (' ')
        timeout(7.6)
        os.system ('python hack.py')
        time.sleep(0.1)
        print (' ttt')
        bnn ()
    else:
        print (' ')
        timeout(0.6)
        print ('.............\033[1;31m(ﺢﯾﺤﺼ ﺮﯾﻏ)\033[92m...............!')
        timeout(0.3)
        print ("")
        print ('.............\033[1;31m(0_0)\033[92m...............!') 
        print (' ')
        timeout(0.6)
        homescreen ()

homescreen ()
